// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA97zrFDlSDxtf2qkonl7F1juObyt0zPLY',
    appId: '1:2581535173:web:7b57f8fa188c906f4693ac',
    messagingSenderId: '2581535173',
    projectId: 'ecoearn-31a1f',
    authDomain: 'ecoearn-31a1f.firebaseapp.com',
    storageBucket: 'ecoearn-31a1f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPeauiybIdNTZ19gP5JD1WUa79uXyRP0s',
    appId: '1:2581535173:android:333bef2cae989fe44693ac',
    messagingSenderId: '2581535173',
    projectId: 'ecoearn-31a1f',
    storageBucket: 'ecoearn-31a1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-5WkRwLcXdXKl82K9BSTZvoWq72zeb2k',
    appId: '1:2581535173:ios:f6a9b35540253bc64693ac',
    messagingSenderId: '2581535173',
    projectId: 'ecoearn-31a1f',
    storageBucket: 'ecoearn-31a1f.firebasestorage.app',
    iosBundleId: 'com.greencrew.ecoearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-5WkRwLcXdXKl82K9BSTZvoWq72zeb2k',
    appId: '1:2581535173:ios:f6a9b35540253bc64693ac',
    messagingSenderId: '2581535173',
    projectId: 'ecoearn-31a1f',
    storageBucket: 'ecoearn-31a1f.firebasestorage.app',
    iosBundleId: 'com.greencrew.ecoearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA97zrFDlSDxtf2qkonl7F1juObyt0zPLY',
    appId: '1:2581535173:web:0de73f8a94ec1ace4693ac',
    messagingSenderId: '2581535173',
    projectId: 'ecoearn-31a1f',
    authDomain: 'ecoearn-31a1f.firebaseapp.com',
    storageBucket: 'ecoearn-31a1f.firebasestorage.app',
  );
}
