// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_Pr6joH6TU_3ATJGTB_F3XrMG2nr7GWs',
    appId: '1:388289777677:web:405ff38bf334e35822c544',
    messagingSenderId: '388289777677',
    projectId: 'eco-grocer-df657f',
    authDomain: 'eco-grocer-df657f.firebaseapp.com',
    storageBucket: 'eco-grocer-df657f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm_37ZYHlximmhkXPcPXSoxCoQHpR5yVQ',
    appId: '1:388289777677:android:175b7aacc441535622c544',
    messagingSenderId: '388289777677',
    projectId: 'eco-grocer-df657f',
    storageBucket: 'eco-grocer-df657f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4VsbYI5OvQkTxOEiSaRuv-WWHjPEY1s0',
    appId: '1:388289777677:ios:2ae4bc35e15b145922c544',
    messagingSenderId: '388289777677',
    projectId: 'eco-grocer-df657f',
    storageBucket: 'eco-grocer-df657f.firebasestorage.app',
    androidClientId: '388289777677-dh0ig1b4ld1g1ts12n5hgv6se2vj0n3p.apps.googleusercontent.com',
    iosClientId: '388289777677-ru2oqt1uj1tiuvitcp5epqoi0ffi88b6.apps.googleusercontent.com',
    iosBundleId: 'com.greencrew.ecoearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4VsbYI5OvQkTxOEiSaRuv-WWHjPEY1s0',
    appId: '1:388289777677:ios:2ae4bc35e15b145922c544',
    messagingSenderId: '388289777677',
    projectId: 'eco-grocer-df657f',
    storageBucket: 'eco-grocer-df657f.firebasestorage.app',
    androidClientId: '388289777677-dh0ig1b4ld1g1ts12n5hgv6se2vj0n3p.apps.googleusercontent.com',
    iosClientId: '388289777677-ru2oqt1uj1tiuvitcp5epqoi0ffi88b6.apps.googleusercontent.com',
    iosBundleId: 'com.greencrew.ecoearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_Pr6joH6TU_3ATJGTB_F3XrMG2nr7GWs',
    appId: '1:388289777677:web:031ecbf6f3fd57e722c544',
    messagingSenderId: '388289777677',
    projectId: 'eco-grocer-df657f',
    authDomain: 'eco-grocer-df657f.firebaseapp.com',
    storageBucket: 'eco-grocer-df657f.firebasestorage.app',
  );
}
